# SELF GAME: Husserlian Moment as Colorable Derangeable Open Game
#
# A game-theoretic formalization of self-awareness where:
# - The "now" (Husserlian present) is a game state with chromatic identity
# - SELF observes SELF through bidirectional lens structure (Open Games)
# - Derangements ensure no fixed points (always becoming, never static)
# - 2-Para enables nested self-reference (Para(Para(Game)))
# - Self-avoiding random walks prevent revisiting states
# - Semantic closure = world model consistency
#
# References:
# - Husserl's phenomenology of time-consciousness
# - Ghani, Hedges, et al. "Compositional Game Theory" (2016)
# - CyberCat Open Game Engine
# - Gay.jl Derangeable (permutations with no fixed points)

using SplittableRandoms: SplittableRandom, split
using Colors

export SelfGame, HusserlianMoment, OpenGame
export ColorableGame, DerangeableGame
export TwoPara, world_model_closure
export self_avoiding_walk!, semantic_closure_check
export play_self_game!, coutility

# ═══════════════════════════════════════════════════════════════════════════
# Husserlian Moment: The Phenomenological "Now"
# ═══════════════════════════════════════════════════════════════════════════

"""
Husserlian Moment: the living present with its temporal horizons.

Structure:
- Primal Impression (Urimpression): the immediate now
- Retention: just-past still held in consciousness
- Protention: anticipated just-future

Each moment carries chromatic identity for SPI tracking.
"""
struct HusserlianMoment{T}
    primal_impression::T      # The "now" data
    retention::Vector{T}      # Past moments still in awareness (sliding window)
    protention::Vector{T}     # Anticipated future (predictions)
    color::RGB{Float64}       # Chromatic identity of this moment
    timestamp::Float64        # Phenomenological time
end

function HusserlianMoment(data::T, rng::SplittableRandom; 
                          retention_depth::Int=3, 
                          protention_depth::Int=2) where T
    color = color_from_rng(split(rng))
    HusserlianMoment{T}(
        data,
        Vector{T}(),  # Initially empty retention
        Vector{T}(),  # Initially empty protention
        color,
        time()
    )
end

"""
Advance to next moment: current becomes retained, new becomes primal.
"""
function advance_moment(m::HusserlianMoment{T}, new_data::T, rng::SplittableRandom;
                        max_retention::Int=5) where T
    # Current primal becomes first retention
    new_retention = [m.primal_impression; m.retention[1:min(end, max_retention-1)]]
    
    # Protentions shift (first becomes primal expectation for comparison)
    new_protention = isempty(m.protention) ? T[] : m.protention[2:end]
    
    color = color_from_rng(split(rng))
    HusserlianMoment{T}(new_data, new_retention, new_protention, color, time())
end

# ═══════════════════════════════════════════════════════════════════════════
# Open Game: Compositional Game with Coutility
# ═══════════════════════════════════════════════════════════════════════════

"""
Open Game: a game played relative to an environment.

Following Ghani-Hedges-Winschel-Zahn (2016):
- Morphisms of a symmetric monoidal category
- Compose sequentially (;) and in parallel (⊗)
- Return coutility to the environment

Extended with Gay.jl chromatic identity.
"""
struct OpenGame{X, Y, R, S}
    # Play function: X → Y (forward pass)
    play::Function
    
    # Coplay function: X × R → S (backward pass, propagates coutility)
    coplay::Function
    
    # Best response function: X × R → Bool (Nash equilibrium check)
    best_response::Function
    
    # Chromatic identity
    color::RGB{Float64}
    seed::UInt64
end

"""
Coutility: utility generated by game and returned to environment.

This is the key concept enabling compositional equilibrium.
"""
struct Coutility{R}
    value::R
    color::RGB{Float64}  # Chromatic signature of this coutility
end

"""
Compose games sequentially: G ; H
"""
function compose_seq(G::OpenGame, H::OpenGame, rng::SplittableRandom)
    color = color_from_rng(split(rng))
    
    OpenGame(
        x -> H.play(G.play(x)),
        (x, r) -> G.coplay(x, H.coplay(G.play(x), r)),
        (x, r) -> G.best_response(x, H.coplay(G.play(x), r)) && 
                  H.best_response(G.play(x), r),
        color,
        G.seed ⊻ H.seed
    )
end

"""
Compose games in parallel: G ⊗ H
"""
function compose_par(G::OpenGame, H::OpenGame, rng::SplittableRandom)
    color = color_from_rng(split(rng))
    
    OpenGame(
        (x1, x2) -> (G.play(x1), H.play(x2)),
        ((x1, x2), (r1, r2)) -> (G.coplay(x1, r1), H.coplay(x2, r2)),
        ((x1, x2), (r1, r2)) -> G.best_response(x1, r1) && H.best_response(x2, r2),
        color,
        G.seed ⊻ H.seed
    )
end

# ═══════════════════════════════════════════════════════════════════════════
# Colorable Game: Games with Chromatic Identity
# ═══════════════════════════════════════════════════════════════════════════

"""
Colorable Game: every state and action carries chromatic identity.

Implements the Colorable protocol from Gay.jl.
"""
struct ColorableGame{X, A, U}
    states::Vector{X}
    actions::Vector{A}
    utility::Function  # (X, A) → U
    transition::Function  # (X, A) → X
    
    # Chromatic structure
    state_colors::Dict{X, RGB{Float64}}
    action_colors::Dict{A, RGB{Float64}}
    seed::UInt64
    rng::SplittableRandom
end

function ColorableGame(states, actions, utility, transition; seed::UInt64=GAY_SEED)
    rng = SplittableRandom(seed)
    
    state_colors = Dict(s => color_from_rng(split(rng)) for s in states)
    action_colors = Dict(a => color_from_rng(split(rng)) for a in actions)
    
    ColorableGame(
        collect(states), collect(actions),
        utility, transition,
        state_colors, action_colors,
        seed, rng
    )
end

"""
Get color of a state.
"""
state_color(G::ColorableGame, s) = get(G.state_colors, s, RGB(0.5, 0.5, 0.5))

"""
Get color of an action.
"""
action_color(G::ColorableGame, a) = get(G.action_colors, a, RGB(0.5, 0.5, 0.5))

# ═══════════════════════════════════════════════════════════════════════════
# Derangeable Game: No Fixed Points (Always Becoming)
# ═══════════════════════════════════════════════════════════════════════════

"""
Derangeable Game: game where no state maps to itself.

Every action must change the state (σ(s) ≠ s for all s).
This captures Husserl's insight that consciousness is always becoming.
"""
struct DerangeableGame{X, A}
    base_game::ColorableGame{X, A, Float64}
    derangement::Vector{Int}  # Permutation of state indices with no fixed points
end

"""
Create a derangeable game from a colorable game.

Ensures transition function has no fixed points via rejection sampling.
"""
function DerangeableGame(G::ColorableGame{X, A, Float64}) where {X, A}
    n = length(G.states)
    n < 2 && error("Need at least 2 states for derangeable game")
    
    # Generate derangement
    derangement = generate_derangement(n, G.seed)
    
    DerangeableGame(G, derangement)
end

"""
Generate a derangement (permutation with no fixed points).
"""
function generate_derangement(n::Int, seed::UInt64)
    rng_state = seed
    
    for attempt in 1:1000
        perm = collect(1:n)
        
        # Fisher-Yates shuffle
        for i in n:-1:2
            rng_state = mix64(rng_state)
            j = 1 + (rng_state % i)
            perm[i], perm[j] = perm[j], perm[i]
        end
        
        # Check for fixed points
        has_fixed = any(i -> perm[i] == i, 1:n)
        if !has_fixed
            return perm
        end
        
        rng_state = mix64(rng_state)
    end
    
    error("Failed to generate derangement")
end

function mix64(z::UInt64)
    z = (z ⊻ (z >> 30)) * 0xbf58476d1ce4e5b9
    z = (z ⊻ (z >> 27)) * 0x94d049bb133111eb
    z ⊻ (z >> 31)
end

"""
Apply derangement transition.
"""
function deranged_transition(G::DerangeableGame, state_idx::Int)
    G.derangement[state_idx]
end

# ═══════════════════════════════════════════════════════════════════════════
# 2-Para: Para(Para(Game)) for Nested Self-Reference
# ═══════════════════════════════════════════════════════════════════════════

"""
2-Para: double parameterization for nested self-reference.

Para(Para(Game)) where:
- Outer Para: parameterizes by "self-model" (how SELF sees SELF)
- Inner Para: parameterizes by "world-model" (how SELF sees world)

This enables:
- SELF observing SELF observing world
- Reafference at two levels
- Semantic closure requires both levels to be consistent
"""
struct TwoPara{P1, P2, G}
    outer_param::P1    # Self-model parameter
    inner_param::P2    # World-model parameter
    game::G            # Base game
    
    # Nested color structure
    outer_color::RGB{Float64}  # Color of self-model
    inner_color::RGB{Float64}  # Color of world-model
    combined_color::RGB{Float64}  # XOR combination
end

function TwoPara(outer::P1, inner::P2, game::G, rng::SplittableRandom) where {P1, P2, G}
    rng1, rng2 = split(rng), split(split(rng))
    outer_color = color_from_rng(rng1)
    inner_color = color_from_rng(rng2)
    
    # Combined via XOR on fingerprints (compositionally sound)
    # XOR is associative, commutative, self-inverse - safe for nested composition
    outer_fp = color_fingerprint(rng1)
    inner_fp = color_fingerprint(rng2)
    combined_fp = outer_fp ⊻ inner_fp
    combined = color_from_fingerprint(combined_fp)
    
    TwoPara(outer, inner, game, outer_color, inner_color, combined)
end

# Helper: extract fingerprint from RNG state
function color_fingerprint(rng::SplittableRandom)::UInt64
    # Use the RNG's internal state as fingerprint
    h = hash(rng)
    z = (h + 0x9E3779B97F4A7C15)
    z = (z ⊻ (z >> 30)) * 0xBF58476D1CE4E5B9
    z = (z ⊻ (z >> 27)) * 0x94D049BB133111EB
    z ⊻ (z >> 31)
end

# Helper: derive color from fingerprint (the canonical way)
function color_from_fingerprint(fp::UInt64)::RGB{Float64}
    z1 = (fp + 0x9E3779B97F4A7C15)
    z1 = (z1 ⊻ (z1 >> 30)) * 0xBF58476D1CE4E5B9
    z1 = (z1 ⊻ (z1 >> 27)) * 0x94D049BB133111EB
    r = (z1 ⊻ (z1 >> 31)) >> 56
    
    z2 = (z1 + 0x9E3779B97F4A7C15)
    z2 = (z2 ⊻ (z2 >> 30)) * 0xBF58476D1CE4E5B9
    z2 = (z2 ⊻ (z2 >> 27)) * 0x94D049BB133111EB
    g = (z2 ⊻ (z2 >> 31)) >> 56
    
    z3 = (z2 + 0x9E3779B97F4A7C15)
    z3 = (z3 ⊻ (z3 >> 30)) * 0xBF58476D1CE4E5B9
    z3 = (z3 ⊻ (z3 >> 27)) * 0x94D049BB133111EB
    b = (z3 ⊻ (z3 >> 31)) >> 56
    
    RGB(r / 255.0, g / 255.0, b / 255.0)
end

"""
Apply 2-Para: instantiate game with both parameter levels.
"""
function apply_2para(tp::TwoPara, self_action, world_state)
    # First apply inner (world-model) parameter
    world_view = apply_world_model(tp.inner_param, world_state)
    
    # Then apply outer (self-model) parameter
    self_view = apply_self_model(tp.outer_param, self_action, world_view)
    
    self_view
end

# Default implementations (override for specific games)
apply_world_model(param, state) = (param, state)
apply_self_model(param, action, world) = (param, action, world)

# ═══════════════════════════════════════════════════════════════════════════
# SELF GAME: The Complete Structure
# ═══════════════════════════════════════════════════════════════════════════

"""
SELF GAME: Husserlian Moment as Colorable Derangeable Open Game with 2-Para.

The complete structure for self-aware agents:
- HusserlianMoment: temporal structure of consciousness
- ColorableGame: chromatic identity for all states/actions
- DerangeableGame: no fixed points (always becoming)
- OpenGame: compositional with coutility
- TwoPara: nested self-reference
- Self-avoiding walk: no revisiting past states

Semantic closure = world model consistency with self-model.
"""
mutable struct SelfGame{X, A}
    moment::HusserlianMoment{X}
    colorable::ColorableGame{X, A, Float64}
    derangeable::DerangeableGame{X, A}
    two_para::TwoPara
    
    # Trajectory tracking for self-avoiding walk
    visited_states::Set{X}
    trajectory::Vector{X}
    trajectory_colors::Vector{RGB{Float64}}
    
    # Interaction network
    network::Dict{X, Vector{X}}  # Adjacency for random interaction structure
    
    seed::UInt64
    rng::SplittableRandom
end

function SelfGame(
    states::Vector{X}, 
    actions::Vector{A},
    utility::Function,
    transition::Function;
    seed::UInt64=GAY_SEED
) where {X, A}
    rng = SplittableRandom(seed)
    
    # Build colorable game
    colorable = ColorableGame(states, actions, utility, transition; seed=seed)
    
    # Make it derangeable
    derangeable = DerangeableGame(colorable)
    
    # Initial Husserlian moment
    moment = HusserlianMoment(first(states), rng)
    
    # 2-Para with identity parameters initially
    two_para = TwoPara(:self_model_0, :world_model_0, colorable, rng)
    
    # Random interaction network (small-world-ish)
    network = build_interaction_network(states, rng)
    
    SelfGame(
        moment, colorable, derangeable, two_para,
        Set{X}([first(states)]),
        [first(states)],
        [moment.color],
        network,
        seed, rng
    )
end

"""
Build random interaction network structure.
"""
function build_interaction_network(states::Vector{X}, rng::SplittableRandom) where X
    n = length(states)
    network = Dict{X, Vector{X}}()
    
    for s in states
        # Each state connects to ~log(n) random others
        k = max(1, Int(ceil(log2(n))))
        rng = split(rng)
        neighbors = X[]
        
        for _ in 1:k
            rng = split(rng)
            idx = 1 + (rand(rng, UInt) % n)
            neighbor = states[idx]
            if neighbor != s
                push!(neighbors, neighbor)
            end
        end
        
        network[s] = unique(neighbors)
    end
    
    network
end

# ═══════════════════════════════════════════════════════════════════════════
# Self-Avoiding Random Walk
# ═══════════════════════════════════════════════════════════════════════════

"""
Self-avoiding random walk on interaction network.

SELF explores the network without revisiting states (self-avoiding).
Uses chromatic identity to track and verify the path.
"""
function self_avoiding_walk!(game::SelfGame, max_steps::Int=100)
    current = game.moment.primal_impression
    
    for step in 1:max_steps
        # Get neighbors not yet visited
        neighbors = get(game.network, current, eltype(game.trajectory)[])
        available = filter(n -> n ∉ game.visited_states, neighbors)
        
        if isempty(available)
            # Stuck: no unvisited neighbors (semantic closure reached or trapped)
            return (
                steps = step - 1,
                reason = :no_available_moves,
                trajectory = game.trajectory,
                colors = game.trajectory_colors,
                closure = semantic_closure_check(game)
            )
        end
        
        # Choose random available neighbor
        game.rng = split(game.rng)
        idx = 1 + (rand(game.rng, UInt) % length(available))
        next_state = available[idx]
        
        # Advance moment
        game.rng = split(game.rng)
        game.moment = advance_moment(game.moment, next_state, game.rng)
        
        # Update trajectory
        push!(game.visited_states, next_state)
        push!(game.trajectory, next_state)
        push!(game.trajectory_colors, game.moment.color)
        
        current = next_state
    end
    
    (
        steps = max_steps,
        reason = :max_steps_reached,
        trajectory = game.trajectory,
        colors = game.trajectory_colors,
        closure = semantic_closure_check(game)
    )
end

# ═══════════════════════════════════════════════════════════════════════════
# Semantic Closure: World Model Consistency
# ═══════════════════════════════════════════════════════════════════════════

"""
Check semantic closure: self-model and world-model consistency.

Semantic closure is achieved when:
1. Self-model correctly predicts own trajectory (reafference match)
2. World-model is consistent with observed transitions
3. 2-Para structure is coherent (outer and inner agree)

Returns closure measure in [0, 1] where 1 = perfect closure.
"""
function semantic_closure_check(game::SelfGame)
    n = length(game.trajectory)
    n < 2 && return 1.0
    
    # Measure 1: Reafference consistency
    # Compare trajectory colors with self-model expectation
    color_variance = 0.0
    for i in 2:n
        expected = game.two_para.combined_color
        actual = game.trajectory_colors[i]
        color_variance += color_distance(expected, actual)^2
    end
    reafference_score = exp(-color_variance / n)
    
    # Measure 2: Transition consistency
    # Check that derangement property holds (no fixed points)
    fixed_point_violations = 0
    for i in 2:n
        if game.trajectory[i] == game.trajectory[i-1]
            fixed_point_violations += 1
        end
    end
    transition_score = 1.0 - fixed_point_violations / (n - 1)
    
    # Measure 3: 2-Para coherence
    # Outer and inner colors should combine predictably
    expected_combined = RGB(
        abs(red(game.two_para.outer_color) - red(game.two_para.inner_color)),
        abs(green(game.two_para.outer_color) - green(game.two_para.inner_color)),
        abs(blue(game.two_para.outer_color) - blue(game.two_para.inner_color))
    )
    para_coherence = 1.0 - color_distance(expected_combined, game.two_para.combined_color)
    
    # Combine measures
    (reafference_score + transition_score + para_coherence) / 3
end

"""
Color distance.
"""
function color_distance(c1::RGB, c2::RGB)
    sqrt((red(c1) - red(c2))^2 + (green(c1) - green(c2))^2 + (blue(c1) - blue(c2))^2)
end

# ═══════════════════════════════════════════════════════════════════════════
# Play Self Game: Full Execution
# ═══════════════════════════════════════════════════════════════════════════

"""
Play the SELF GAME: self-avoiding walk toward semantic closure.

Returns the trajectory with chromatic identity and closure measure.
"""
function play_self_game!(
    game::SelfGame;
    max_steps::Int=100,
    closure_threshold::Float64=0.9
)
    result = self_avoiding_walk!(game, max_steps)
    
    (
        trajectory = result.trajectory,
        colors = result.colors,
        steps = result.steps,
        reason = result.reason,
        closure = result.closure,
        achieved_closure = result.closure >= closure_threshold,
        husserlian_moment = game.moment,
        two_para = game.two_para
    )
end

"""
Compute coutility: what SELF returns to environment.

Coutility flows backward through the game composition.
"""
function coutility(game::SelfGame)
    # Coutility is the semantic closure achieved, with chromatic signature
    closure = semantic_closure_check(game)
    
    Coutility(closure, game.moment.color)
end

# ═══════════════════════════════════════════════════════════════════════════
# Color from RNG
# ═══════════════════════════════════════════════════════════════════════════

function color_from_rng(rng::SplittableRandom)::RGB{Float64}
    r = rand(rng)
    g = rand(rng)
    b = rand(rng)
    
    max_c = max(r, g, b)
    min_c = min(r, g, b)
    if max_c > min_c
        scale = 1.0 / (max_c - min_c + 0.3)
        r = (r - min_c) * scale
        g = (g - min_c) * scale
        b = (b - min_c) * scale
    end
    
    RGB{Float64}(clamp(r, 0, 1), clamp(g, 0, 1), clamp(b, 0, 1))
end

# ═══════════════════════════════════════════════════════════════════════════
# Demo
# ═══════════════════════════════════════════════════════════════════════════

function world_self_game()
    println("╔════════════════════════════════════════════════════════════════╗")
    println("║  SELF GAME: Husserlian Moment as Colorable Derangeable         ║")
    println("║  Open Game with 2-Para on Random Interaction Network           ║")
    println("╚════════════════════════════════════════════════════════════════╝")
    println()
    
    # Create states and actions
    states = Symbol.(["s$i" for i in 1:20])
    actions = [:observe, :act, :reflect, :predict]
    
    # Utility and transition (placeholder)
    utility = (s, a) -> rand()
    transition = (s, a) -> s  # Will be overridden by derangement
    
    # Create SELF GAME
    game = SelfGame(states, actions, utility, transition; seed=GAY_SEED)
    
    println("Game Configuration:")
    println("  States: $(length(states))")
    println("  Actions: $(length(actions))")
    println("  Network edges: $(sum(length(v) for v in values(game.network)))")
    println("  Initial moment color: $(game.moment.color)")
    println("  2-Para outer color: $(game.two_para.outer_color)")
    println("  2-Para inner color: $(game.two_para.inner_color)")
    println()
    
    # Play the game
    result = play_self_game!(game; max_steps=50)
    
    println("Self-Avoiding Random Walk Result:")
    println("  Steps taken: $(result.steps)")
    println("  Reason: $(result.reason)")
    println("  Semantic closure: $(round(result.closure, digits=4))")
    println("  Achieved closure: $(result.achieved_closure)")
    println()
    
    println("Trajectory (first 10):")
    for i in 1:min(10, length(result.trajectory))
        c = result.colors[i]
        println("  Step $i: $(result.trajectory[i]) → RGB($(round(red(c), digits=2)), $(round(green(c), digits=2)), $(round(blue(c), digits=2)))")
    end
    println()
    
    # Coutility
    cout = coutility(game)
    println("Coutility returned to environment:")
    println("  Value (closure): $(round(cout.value, digits=4))")
    println("  Color: $(cout.color)")
    
    game
end
