(gat
  (ob TestWitness)
  (ob ClosureAspect)
  (ob CounterfactualAssignment)
  (ob CatColabDecl)
  (ob LispForm)
  (ob SharedArena)
  (attrtype Color)
  (attrtype Trit)
  (attrtype Cost)
  (attrtype CounterfactualEffect)
  (attrtype ScipAddress)
  (hom has-aspect TestWitness ClosureAspect)
  (hom has-counterfactual TestWitness CounterfactualAssignment)
  (hom from-aspect CounterfactualAssignment ClosureAspect)
  (hom to-aspect CounterfactualAssignment ClosureAspect)
  (hom declares-object ClosureAspect CatColabDecl)
  (hom as-declared-object CounterfactualAssignment CatColabDecl)
  (hom observed-as LispForm TestWitness)
  (hom language-assigns-aspect LispForm ClosureAspect)
  (hom shared-in CounterfactualAssignment SharedArena)
  (hom witness-arena TestWitness SharedArena)
  (attr witness-color TestWitness Color)
  (attr aspect-trit ClosureAspect Trit)
  (attr counterfactual-cost CounterfactualAssignment Cost)
  (attr counterfactual-effect CounterfactualAssignment CounterfactualEffect)
  (attr scip-uri CatColabDecl ScipAddress)
  (eq (compose has-counterfactual from-aspect)
      (compose has-aspect))
  (eq (compose has-counterfactual to-aspect declares-object)
      (compose has-counterfactual as-declared-object))
  (eq (compose observed-as has-aspect)
      (compose language-assigns-aspect))
  (eq (compose has-counterfactual shared-in)
      (compose witness-arena)))
